### ISSUE TITLE
Update to WebExtensions

### ISSUE THREAD

**Issue by sputnik1** [Albirew/resurrect-pages-isup-edition#10]
If you can possibly spare the time, please convert Resurrect Pages to WebExtensions. Many like myself have used your add-on for years and would greatly appreciate your effort. Thank you.

**Comment by Reoldyk** [comment]
you can use this as alternative.
https://addons.mozilla.org/en-US/firefox/addon/archiver-menu/

**Comment by Albirew** [comment]
Unfortunately, I'm not much of a dev so I'm basically sticking with original developer's updates adding very little changes.

Also, webextensions cannot interact with firefox internal code like XUL does so custom error pages would very likely be impossible to do.

I'll keep this issue open but things as it is, using Reoldyk's found addon Archive-menu would be the best alternative.

**Comment by Albirew** [comment]
Thanks, I updated using latest master from Arantius.
It might take some time until this version is pushed at AMO.
