### ISSUE TITLE
Module n'est plus affiché dans le menu contextuel de Firefox / Add-on is no longer displayed in contextual menu.

### ISSUE THREAD

**Issue by TheOneBehindYou** [Albirew/resurrect-pages-isup-edition#11]
Bonjour,
Je présume depuis la dernière mise à jour de votre module sur Firefox, celui-ci n'est plus affiché dans le menu contextuel (clic droit).
J'utilise Firefox 59.0.2 x64.
Merci. Cordialement.
------------------------------------------------------------------------------------------------------------
The add-on is not displayed in the contextual menu (right click). I think since the last update. I see that three days after.
I'm using Firefox 59.0.2 x64.
Tested with all others add-on disabled and on a fresh install.
Thank you. Regards

**Comment by Albirew** [comment]
Corrigé dans la version 6.1 grâce au PR #13
