### ISSUE TITLE
Clean up dead hosts and update live ones

### ISSUE THREAD

**Issue by alexolog** [Albirew/resurrect-pages-isup-edition#2]
1. Google cache redirects to  webcache.googleusercontent.com -- use that instead.
2. Coral CDN (nyud.net) does not seem to work for anything -- the pages do not resolve.
3. Yahoo generates an internal error and hangs until [cancel] is pressed.
4. Gigablast generates an internal error and hangs until [cancel] is pressed.
5. ~~Wayback Machine sometimes fails to work due to the presence of parameters on the URL -- they should be stripped off.
   For example: http://blogs.msdn.com/b/vcblog/archive/2013/06/28/using-visual-studio-2013-to-write-maintainable-native-visualizations-natvis.aspx?Redirected=true
   The "?Redirected=true" is the problem.~~
6. Bing just performs a regular search, although following the links to cached content is possible.

**Comment by Albirew** [comment]
The problem with 5 is that websites using parameters as page IDs like forums won't show the cached topic and will instead get either a "not cached" error or will get to the forum/site root.

**Comment by alexolog** [comment]
Does Wayback even cache such pages?

**Comment by Albirew** [comment]
Definitively, yes.
An example I have in my history:
http://web.archive.org/web/20081113001724/http://webrunr.com/content/show_flash.php?id=1
http://web.archive.org/web/20081113001736/http://webrunr.com/content/show_flash.php?id=2

**Comment by alexolog** [comment]
removed #5

**Comment by alexolog** [comment]
Any chance of addressing the other concerns?

**Comment by Albirew** [comment]
3 & 4 are actually the same as 1st issue in #1 and I'm trying to figure out how can I do this without rewriting the whole addon from scratch...

**Comment by alexolog** [comment]
as a stopgap measure, maybe just fix the yahoo and gigablast redirection?

**Comment by Albirew** [comment]
Well, it seems like yahoo has stopped caching and redirect users to bing cache so I just removed it (along with coral since it's almost always dead)
For gigablast, it's... more complicated. Their API is so 2000's and needs:
1) search dead link using their API
2) getting results
3) trim result's DocID from API answer
4) redirect user to gigablast new URL with this DocID

a lot of work ahead

**Comment by alexolog** [comment]
So, to summarize:
1. Google cache needs a different URL.
2. Coral CDN will be removed.
3. Yahoo will be removed.
4. Gigablast will be removed (temporarily until fixed, or permanently).
5. Wayback works as designed, nothing to do.
6. Bing needs rework.

Do you agree?

**Comment by Albirew** [comment]
yes, this pretty much summarize.
I didn't have searched very throughly but I saw bing search API is not free so directly accessing bing cache may be tricky.

**Comment by alexolog** [comment]
Suggestion:

Do a "url:" search on Bing.  For example: https://www.bing.com/search?q=url%3Awww.catsthemusical.com

The cached page would be found in:
http://cc.bingj.com/cache.aspx?q=url%3awww.catsthemusical.com&d=5064463656813710&w=utKTorR8DnP_DWJIzZ5BnhMOhdT8Mwjd

I was able to find the two parameters in the page source:
<ol id="b_results">
<li class="b_algo">
<h2><a href="http://www.catsthemusical.com/" h="ID=SERP,5084.1"><strong>Cats</strong> the Musical - Official Site</a></h2>
<div class="b_caption">
<div class="b_attribution" u="0N|5076|5064463656813710|utKTorR8DnP_DWJIzZ5BnhMOhdT8Mwjd">

(note that "b_caption" and "b_attribution" appeared twice in that page so the path may be important)

Sounds doable
