### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Reoldyk** [Albirew/resurrect-pages-isup-edition#8]
Bisakah anda untuk menambahkan fitur seperti chrome extension ini?
untuk menambahkan halaman ke wayback machine.

(translate to english)
Can you add feature like this chrome extension?
add page to wayback machine.
https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak/

(sorry for my bad english)

**Comment by Albirew** [comment]
Wayback machine already in list (called "The Internet Archive")

google TL: Wayback machine sudah ada dalam daftar (disebut "The Internet Archive")
