### ISSUE TITLE
Corrupted install

### ISSUE THREAD

**Issue by iBeny** [Albirew/resurrect-pages-isup-edition#9]
Hi
Used Resurrect Pages for many years and now I found it disactivated for it not being... "verified" in Firefox 43.01 !

OK ! I then searched in Firefox extension (add-on) bank for another Resurrect Page add-on and found that this one here was compatible with my FF. I tried then to install it but couldn't because it is deemed to be... "corrupted" !? There is another Resurrect Page add-on that also refused to install for the same reason ! Both are... "corrupted" !?

What's up doc ?

Best regards,
iBeny``

**Comment by Albirew** [comment]
Latest version of firefox does not allow addons that are not compatible with e10s (multiprocess firefox)
I'm not much of a dev myself, this addon being only a fork of the one from Arantius with a website checker added (isup.me), so if he fix it, I'll also "fix" it.
See https://github.com/arantius/resurrect-pages/issues/26
